### ISSUE TITLE
Visualize the trees

### ISSUE THREAD

**Issue by harshakokel** [hayesall/srlearn#56]
**Describe if the Java version of BoostSRL already supports this.**
Boost SRL provides dotfiles

**Is your feature request related to a problem? Please describe.**
Visualizing the tree is the best way to analyzing the boostSRL model. Serialization helps in quantitative analysis but the visualization helps in qualitative analysis.

**Describe the solution you'd like**
Perhaps something like similar to [`sklearn.tree.export_graphviz`](https://scikit-learn.org/stable/modules/generated/sklearn.tree.export_graphviz.html)
```
clf = BoostRDN()
clf.fit()
estimator_1_dot = tree.export_graphviz(clf, estimator=1)
```

**Comment by hayesall** [comment]
Related to #28 (make graphviz optional)

There's a version of this in the deprecated `boostsrl.py` that could export images to files, or return them directly (e.g. to show in Jupyter notebooks).

https://github.com/hayesall/srlearn/blob/973afbcee8b86fb1bdec2eb1e313c4973abde914/srlearn/boostsrl.py#L314-L346

**Comment by harshakokel** [comment]
But this has a limitation, it will only work when the FileSystem is around.

**Comment by hayesall** [comment]
Good point. That also means we should serialize them during `to_json` calls, otherwise we won't be able to:

```python
>>> rdn = BoostedRDN()
>>> rdn.from_json("saved_model.json")
>>> export_graphviz(rdn, estimator=0)
```

LightGBM might be closer to what we want here, I might pull ideas from both of these:

- [`sklearn.tree.export_graphviz`](https://scikit-learn.org/stable/modules/generated/sklearn.tree.export_graphviz.html)
- [`lightgbm.create_tree_digraph`](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.create_tree_digraph.html)
